spring.application.name=cadastro.usuarios
spring.datasource.url=jdbc:h2:file:./data/nomeBanco
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


#configurando JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configurando habilitação do console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
